package com.arcturus.appserver.system.app.type.js.script;

public interface ScriptConstants // NOSONAR
{
	String ENTITY_USECASE_VISIBILITY_PUBLIC = "pub";
	String ENTITY_USECASE_VISIBILITY_PRIVATE = "pri";

	String ENTITY_USECASE_CREATEORLOAD_CREATE = "create";
	String ENTITY_USECASE_CREATEORLOAD_LOAD = "load";

	String ARC_FUNCTION_PREFIX = "arc_";

	// Global
	String FUNC_ENTITY_SERVICES_WITH_PREFIX = ARC_FUNCTION_PREFIX + "findEntityServices";

	String FUNC_FIND_USECASES = "findUseCases";
	String FUNC_FIND_USECASES_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_FIND_USECASES;

	String FUNC_FIND_LIST_SERVICES = "findListServices";
	String FUNC_FIND_LIST_SERVICES_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_FIND_LIST_SERVICES;

	String FUNC_FIND_ENTITY_SERVICES_WITH_UPDATE = "findServicesWithUpdate";
	String FUNC_FIND_ENTITY_SERVICES_WITH_UPDATE_WITH_PREFIX = ARC_FUNCTION_PREFIX
		+ FUNC_FIND_ENTITY_SERVICES_WITH_UPDATE;

	// Per service
	String FUNC_FIND_ENTITY_USECASES = "findEntityServiceUseCases";
	String FUNC_FIND_ENTITY_USECASES_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_FIND_ENTITY_USECASES;

	String FUNC_FIND_ENTITY_MAPPERS = "findEntityMappers";
	String FUNC_FIND_ENTITY_MAPPERS_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_FIND_ENTITY_MAPPERS;

	String FUNC_FIND_ENTITY_TRANSACTION_USECASES = "findEntityTransactionServiceUseCases";
	String FUNC_FIND_ENTITY_TRANSACTION_USECASES_WITH_PREFIX = ARC_FUNCTION_PREFIX
		+ FUNC_FIND_ENTITY_TRANSACTION_USECASES;

	String FUNC_ENTITY_USECASE = "entityUseCase";
	String FUNC_ENTITY_USECASE_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_ENTITY_USECASE;

	String FUNC_ENTITY_MAPPER = "entityMapper";
	String FUNC_ENTITY_MAPPER_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_ENTITY_MAPPER;

	String FUNC_ENTITY_TRANSACTION_USECASE_VALIDATE = "entityTransactionUseCaseValidate";
	String FUNC_ENTITY_TRANSACTION_USECASE_VALIDATE_WITH_PREFIX = ARC_FUNCTION_PREFIX
		+ FUNC_ENTITY_TRANSACTION_USECASE_VALIDATE;

	String FUNC_ENTITY_TRANSACTION_USECASE_COMMIT = "entityTransactionUseCaseCommit";
	String FUNC_ENTITY_TRANSACTION_USECASE_COMMIT_WITH_PREFIX = ARC_FUNCTION_PREFIX
		+ FUNC_ENTITY_TRANSACTION_USECASE_COMMIT;

	String FUNC_USECASE = "useCase";
	String FUNC_USECASE_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_USECASE;

	String FUNC_DEFAULT_ENTITY = "defaultEntity";
	String FUNC_DEFAULT_ENTITY_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_DEFAULT_ENTITY;

	String FUNC_INIT_ENTITY = "initEntity";
	String FUNC_INIT_ENTITY_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_INIT_ENTITY;

	String VAL_CURRENT_VERSION = "currentVersion";
	String FUNC_CURRENT_VERSION_WITH_PREFIX = ARC_FUNCTION_PREFIX + VAL_CURRENT_VERSION;

	String FUNC_MIGRATE_TO_V = "migrateToV";
	String FUNC_MIGRATE_TO_V_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_MIGRATE_TO_V;

	String FUNC_UPDATE = "update";
	String FUNC_UPDATE_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_UPDATE;

	String FUNC_PROCESS_GLOBALS = "processGlobals";
	String FUNC_PROCESS_GLOBALS_WITH_PREFIX = ARC_FUNCTION_PREFIX + FUNC_PROCESS_GLOBALS;
}